"""portfs

Revision ID: 3db4c53ba00d
Revises: 
Create Date: 2023-03-26 10:28:22.275970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db4c53ba00d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfs', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
