"""probando

Revision ID: 6480cae501b8
Revises: 0190cf0e7d06
Create Date: 2023-03-31 15:58:57.882844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6480cae501b8'
down_revision = '0190cf0e7d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carID', sa.String(length=255), nullable=True),
    sa.Column('plate', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('year', sa.DateTime(), nullable=True),
    sa.Column('serialBodywork', sa.String(length=255), nullable=True),
    sa.Column('serialMotor', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('problem', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
