"""empty message

Revision ID: 68a5ed47666a
Revises: 75f7f8cd744c
Create Date: 2023-05-09 20:29:31.962270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a5ed47666a'
down_revision = '75f7f8cd744c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('solution', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.drop_column('solution')
        batch_op.drop_column('observations')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
