"""empty message

Revision ID: 75f7f8cd744c
Revises: 89aae197337e
Create Date: 2023-05-09 19:44:06.414564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f7f8cd744c'
down_revision = '89aae197337e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departments_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cars_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_data_cars_id_cars'), 'cars', ['cars_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_project_data_users_id_users'), 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_project_data_departments_id_departments'), 'departments', ['departments_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_data_departments_id_departments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_data_users_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_data_cars_id_cars'), type_='foreignkey')
        batch_op.drop_column('cars_id')
        batch_op.drop_column('users_id')
        batch_op.drop_column('departments_id')

    # ### end Alembic commands ###
