"""changed portf start is began

Revision ID: f0e198b6d043
Revises: ca750864ace3
Create Date: 2023-03-04 00:23:38.899907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e198b6d043'
down_revision = 'ca750864ace3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('began', sa.DateTime(), nullable=True))
        batch_op.drop_column('start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DATETIME(), nullable=True))
        batch_op.drop_column('began')

    # ### end Alembic commands ###
